"I contain one very long method."
Class {
	#name : 'LongMethodExample',
	#superclass : 'Object',
	#instVars : [ 'total' ],
	#package : 'Smelly-Core'
}

{ #category : 'running' }
LongMethodExample >> runEverything [
	total := 0.
	total := total + 1.
	total := total + 2.
	total := total + 3.
	total := total + 4.
	total := total + 5.
	total := total + 6.
	total := total + 7.
	total := total + 8.
	total := total + 9.
	total := total + 10.
	total := total + 11.
	total := total + 12.
	total := total + 13.
	total := total + 14.
	total := total + 15.
	total := total + 16.
	total := total + 17.
	total := total + 18.
	total := total + 19.
	total := total + 20.
	total := total + 21.
	total := total + 22.
	total := total + 23.
	total := total + 24.
	total := total + 25.
	total := total + 26.
	^ total
]
